import Controls from "./components/Controls";
import React, { useState } from "react";
import FractalCanvas from "./components/FractalCanvas";

import SierpinskiIMG from "./assets/SierpinskiTriangle.jpg";
import RomanescoIMG from "./assets/RomanescoIMG.jpg";
import BloodIMG from "./assets/BloodVessels.jpg";
import CoastlineIMG from "./assets/Coastline.jpg";
import SierpinskiGIF from "./assets/Sierpinski_chaos_animated.gif";
import KochSnowIMG from "./assets/KochSnowflake.png";
import KochVisIMG from "./assets/KochVis.png";
import LichenbergIMG from "./assets/LichtenbergFig.jpg";

const h1Style = {
  fontFamily: "'Courier New', Courier, monospace",
  fontSize: "22px",
  letterSpacing: "3px",
  textTransform: "uppercase",
  color: "#b48818",
  borderBottom: "1px solid #3c3418",
  paddingBottom: "10px",
  marginBottom: "24px",
};

const h2Style = {
  fontFamily: "'Courier New', Courier, monospace",
  fontSize: "13px",
  letterSpacing: "2px",
  textTransform: "uppercase",
  color: "#b48818",
  marginTop: "32px",
  marginBottom: "12px",
};

const pStyle = {
  fontFamily: "Georgia, 'Times New Roman', serif",
  fontSize: "15px",
  lineHeight: "1.8",
  color: "#b89e66",
  marginBottom: "14px",
  textIndent: "30px"
};

const imgStyle = {
  width: "50%",
  margin: "20px auto",
  display: "block",
  border: "1px solid #3c3418",
  padding: "4px",
  backgroundColor: "#0c0a06"
};

const aStyle = {
  fontFamily: "Georgia, 'Times New Roman', serif",
  fontSize: "15px",
  lineHeight: "1.8",
  color: "#b89e66",
  marginBottom: "14px",
  textIndent: "30px",
  display: "block"
};

function Article() {
  return (
    <div style={{
      backgroundColor: "#0c0a06",
      minHeight: "100vh",
      padding: "40px 20px",
    }}>
      <div style={{ maxWidth: "680px", margin: "0 auto" }}>
        <h1 style={h1Style}>About Fractals</h1>

        <h2 style={h2Style}>Fractals</h2>
        <p style={pStyle}>
          A fractal is a geometric shape that is infinitely detailed as you zoom in. As you take a closer look at these shapes, you often find the same patterns recurring within the larger shape.
        </p>
        <img src={SierpinskiIMG} alt="Sierpinski Triangle" style={imgStyle} />
        <p style={pStyle}>
          For example, in the Sierpiński triangle without zooming in, the general shape is an equilateral triangle with smaller triangles removed. As we zoom in further, we see that these removed triangles become infinitely smaller, and we see some of the same patterns appearing.
        </p>

        <h2 style={h2Style}>Chaos Game</h2>
        <p style={pStyle}>
          The chaos game is a way of plotting out certain fractals, particularly the Sierpiński triangle. To begin, plot the vertices of an equilateral triangle. Then, you start with a random point inside of the polygon. After this, each iteration you choose a random corner and travel to the midpoint between your position and the corner. This becomes your new point. Iterate this process until a pattern emerges. While the process may sound convoluted, after enough iterations, you will see the Sierpiński triangle appear.
        </p>
        <img src={SierpinskiGIF} alt="Animated Sierpinski Triangle GIF" style={imgStyle} />

        <h2 style={h2Style}>Koch Visualization and Lichtenberg Lightning</h2>
        <p style={pStyle}>
          The Koch snowflake is a fractal where a triangle has smaller equilateral triangles added onto the middle of its three sides. After each iteration, another set of smaller triangles are added onto the middle of the newest triangles sides. The Koch visualization on this website is the same process, but instead triangles are taken out of the middle of its sides, and then the process is repeated with the sides of previously removed triangles. 
        </p>
        <div style={{ display: "flex", justifyContent: "center", gap: "20px" }}>
          <img src={KochSnowIMG} alt="Koch Snowflake" style={{ ...imgStyle, width: "45%"}} />
          <img src={KochVisIMG} alt="Koch Visualization" style={{ ...imgStyle , width: "45%"}} />
        </div>
        <p style={pStyle}>
          Lichtenberg figures are branching figures that model electricity. These figures have fractal properties due to their repeating patterns in the branches of electricity. Similarly, lightning is also known to exhibit fractal properties. The Lichtenberg lighting model is generated by a line growing incrementally while having a random chance to branch off and change direction. The lightning increments are programmed to trend downwards, and when increments break off from the main branch they get thinner. Though the patterns are random, fractal behavior is still exhibited by the model.
        </p>
        <img src={LichenbergIMG} alt="Lichtenberg Figure" style={imgStyle} />

        <h2 style={h2Style}>Practical Uses of Fractals</h2>
        <p style={pStyle}>
          While at first one may assume fractals have little importance for everyday life, fractals are actually utilized in multiple different disciplines and they have lots of real world applications.
          In our natural world, fractals appear everywhere. We can see smaller and smaller repeating patterns appear on things like ferns, snowflakes, pinecones, blood vessels, lightning and romanesco broccoli. Coastlines, while maybe not having repeating patterns, still have infinitely more curves and shapes as you look closer.
        </p>
        <div style={{ display: "flex", justifyContent: "center", gap: "20px" }}>
          <img src={RomanescoIMG} alt="Romanesco Broccoli" style={{ ...imgStyle, width: "45%"}} />
          <img src={CoastlineIMG} alt="Coastline" style={{ ...imgStyle , width: "45%"}} />
        </div>
        <p style={pStyle}>
          Fractals also have applications with computer graphics and VFX. Fractal algorithms can be used to generate realistic effects, such as terrain, clouds, and flora. Because of how little data it takes to generate the intricate patterns of fractals, using fractals keeps computer graphics very data-efficient.
          The human body has some structures that resemble fractals, such as the formation of blood vessel cells and neurons. When something is wrong, oftentimes the fractals in these structures disappear. Using fractals, different types of screenings become more effective at detecting medical issues.
        </p>
        <img src={BloodIMG} alt="Blood Vessels" style={imgStyle} />
        <p style={pStyle}>
          A specific fractal modeled on this website, the mandelbulb, has specifically had many artistic applications. In the movie Big Hero 6, the inside of the wormhole is depicted as part of a mandelbulb's interior. In the movie Annihilation, a mandelbulb represents one of the aliens. Marvel has also used the mandelbulb multiple times, such as in Agents of S.H.I.E.L.D and Doctor Strange where alternate dimensions are depicted using mandelbulbs.
        </p>
        <h2 style={h2Style}>Sources:</h2>
        <a href="https://uwaterloo.ca/math/news/top-5-applications-fractals" target="_blank" rel="noopener noreferrer" style= {aStyle}>
          https://uwaterloo.ca/math/news/top-5-applications-fractals

        </a>

        <a href="https://www.geeksforgeeks.org/maths/real-life-applications-of-fractals/" target="_blank" rel="noopener noreferrer" style= {aStyle}>
          https://www.geeksforgeeks.org/maths/real-life-applications-of-fractals/

        </a>

        <a href="https://www.mathnasium.com/math-centers/hydepark/news/fractals-in-nature" target="_blank" rel="noopener noreferrer" style= {aStyle}>
          https://www.mathnasium.com/math-centers/hydepark/news/fractals-in-nature

        </a>

        <a href="https://math.hws.edu/eck/js/mandelbrot/MB.html" target="_blank" rel="noopener noreferrer" style= {aStyle}>
          https://math.hws.edu/eck/js/mandelbrot/MB.html

        </a>

        <a href="https://math.hws.edu/eck/js/chaos-game/CG.html" target="_blank" rel="noopener noreferrer" style= {aStyle}>
          https://math.hws.edu/eck/js/chaos-game/CG.html

        </a>

        <a href="https://observablehq.com/@mcmcclur/the-koch-snowflake" target="_blank" rel="noopener noreferrer" style= {aStyle}>
          https://observablehq.com/@mcmcclur/the-koch-snowflake

        </a>
      </div>
    </div>
  );
}

export default Article;
